version: '3.3'

services:

  redis-master:
    image: ascent/redis-sentinel:${RELEASE_VERSION:-latest}
    environment:
      - START_COMMAND=sh /redis/redis-wrapper.sh
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${REDIS_VAULT_TOKEN}
    networks:
      - ascentnet
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    deploy:
      placement:
        constraints:
        - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 10s
    healthcheck:
      test: ["CMD", "/usr/local/bin/envconsul", "-config=/redis/template/envconsul-config.hcl", "-vault-addr=${VAULT_ADDR:-http://vault:8200}", "-vault-token=${VAULT_TOKEN:-vaultroot}", "/usr/local/bin/checkhealth.sh", "6379"]

  redis-slave:
    image: ascent/redis-sentinel:${RELEASE_VERSION:-latest}
    environment:
      - START_COMMAND=sh /redis/redis-wrapper.sh --slaveof redis-master 6379
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${REDIS_VAULT_TOKEN}
    links:
      - redis-master
    networks:
      - ascentnet
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    deploy:
      placement:
        constraints:
        - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 10s
    healthcheck:
      test: ["CMD", "/usr/local/bin/envconsul", "-config=/redis/template/envconsul-config.hcl", "-vault-addr=${VAULT_ADDR:-http://vault:8200}", "-vault-token=${VAULT_TOKEN:-vaultroot}", "/usr/local/bin/checkhealth.sh", "6379"]


  # Instance 1
  redis-sentinel:
    image: ascent/redis-sentinel:${RELEASE_VERSION:-latest}
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${REDIS_VAULT_TOKEN}
    links:
      - redis-master
    networks:
      - ascentnet
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    deploy:
      placement:
        constraints:
        - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 10s
    healthcheck:
      test: ["CMD", "/usr/local/bin/envconsul", "-config=/redis/template/envconsul-config.hcl", "-vault-addr=${VAULT_ADDR:-http://vault:8200}", "-vault-token=${VAULT_TOKEN:-vaultroot}", "/usr/local/bin/checkhealth.sh", "26379"]


  # Instance 2
  redis-sentinel2:
    image: ascent/redis-sentinel:${RELEASE_VERSION:-latest}
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${REDIS_VAULT_TOKEN}
    links:
      - redis-master
    networks:
      - ascentnet
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    deploy:
      placement:
        constraints:
        - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 10s
    healthcheck:
      test: ["CMD", "/usr/local/bin/envconsul", "-config=/redis/template/envconsul-config.hcl", "-vault-addr=${VAULT_ADDR:-http://vault:8200}", "-vault-token=${VAULT_TOKEN:-vaultroot}", "/usr/local/bin/checkhealth.sh", "26379"]

  # Instance 3
  redis-sentinel3:
    image: ascent/redis-sentinel:${RELEASE_VERSION:-latest}
    environment:
      - VAULT_ADDR=${VAULT_ADDR}
      - VAULT_TOKEN=${REDIS_VAULT_TOKEN}
    links:
      - redis-master
    networks:
      - ascentnet
    logging:
      driver: fluentd
      options:
        fluentd-async-connect: "true"
        fluentd-max-retries: "10"
        fluentd-retry-wait: "30s"
    deploy:
      placement:
        constraints:
        - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 10s
    healthcheck:
      test: ["CMD", "/usr/local/bin/envconsul", "-config=/redis/template/envconsul-config.hcl", "-vault-addr=${VAULT_ADDR:-http://vault:8200}", "-vault-token=${VAULT_TOKEN:-vaultroot}", "/usr/local/bin/checkhealth.sh", "26379"]

networks:
 ascentnet:
    driver: overlay
